version: '3.5'
networks:
  nativex:
    name: nativex

services:
  nats:
    image: nats:latest
    ports:
      - "${NATS_CLIENT_PORT-4222}:4222"
      - "${NATS_MONITOR_PORT-8222}:8222"
    networks: [ nativex ]

  redis:
    image: redis:alpine
    networks: [ nativex ]

  mongo:
    image: mongo:3.6
    command: --quiet
    volumes:
      - mongo:/data/db
    ports:
      - "${MONGO_PORT-8101}:27017"
    networks: [ nativex ]

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.3
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "plugin.mandatory: analysis-phonetic"
      - "logger.level=WARN"
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - esplug:/usr/share/elasticsearch/plugins
    ports:
      - "${ES_NODE_PORT-8102}:9200"
      - "${ES_TRANSPORT_PORT-8103}:9300"
    depends_on:
      - elasticsearch-plugins
    networks: [ nativex ]

  elasticsearch-plugins:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.3
    entrypoint: sh -c 'test -d "plugins/analysis-phonetic" || bin/elasticsearch-plugin install -s analysis-phonetic'
    tty: true
    volumes:
      - esplug:/usr/share/elasticsearch/plugins

  elasticsearch-kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.3
    environment:
      - server.name=kibana
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - LOGGING_QUIET=true
    ports:
      - "${ES_KIBANA_PORT-8104}:5601"
    depends_on:
      - elasticsearch
    networks: [ nativex ]

volumes:
  mongo: {}
  esdata: {}
  esplug: {}

