version: '3'
services:
  app:
    build: .
    ports:
      - "${GRAPH_APP_PORT-8100}:8100"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    depends_on:
      - redis
      - mongo
    restart: on-failure
    entrypoint: node_modules/.bin/gulp
    environment:
      NODE_ENV: development
      MONGO_DSN: mongodb://mongo:27017/fortnight
      REDIS_DSN: redis://redis:6379/0
      PORT: ${GRAPH_APP_PORT-8100}
      MONGOOSE_DEBUG: ${MONGOOSE_DEBUG}
      DEBUG: ${DEBUG}
  redis:
    image: redis:alpine
  mongo:
    image: mongo:3.4
    volumes:
      - mongodb:/data/db
    ports:
      - "${GRAPH_DB_PORT-8101}:27017"
volumes:
  node_modules: {}
  mongodb: {}
